### ISSUE TITLE
possible to add generate entity for typeorm?

### ISSUE THREAD

**Issue by 646826** [MariusAlch/json-to-ts#12]
I need to convert JSON data in typeORM entity.
Can you add this function to your library?

**Comment by moltar** [comment]
IMO, this is outside of the scope of this library as TypeORM entities are not types, but rather classes with specual decorators.

What you probably should do is generate an interface with this library, and then use it as `implements`.

```ts
class SomeEntity extends Entity implements InterfaceGeneratedByThisLibrary {
  foo: number
  bar: string
}
```

**Comment by MariusAlch** [comment]
I agree. Converting JSON to typeorm entity is an entirely different thing compared to what is lib suppose to do.
