### ISSUE TITLE
Not detecting date objects correctly

### ISSUE THREAD

**Issue by moltar** [MariusAlch/json-to-ts#14]
Yes, technically, JSON does not have a date type.

But I think it is a common use case to convert in memory JS object, which may contain a `Date` object.

Right now it gets cast as `object`.

```ts
interface Row {
  period: string;
  periodStartDay: object;
  periodEndDay: object; // should be Date
}
```

**Comment by MariusAlch** [comment]
Even though Date is not a JSON type I added Date handling :)
