### ISSUE TITLE
null is not handled correctly

### ISSUE THREAD

**Issue by mknj** [MariusAlch/json-to-ts#17]
null is treated as a non existing member. This is not correct.
i.e. 
```js
JSON.parse('{ "something":  [ {"x":1},{"x":"a"},{"x":null} ]}')
```
returns 
```js
{ something: [ { x: 1 }, { x: 'a' }, { x: null } ] }
```

So
```js
{ "something":  [ {"x":1},{"x":"a"},{"x":null} ]}
```
should produce
```js
export interface RootObject {
  something: Something[];
}
export interface Something {
  x: number | string | null;
}
```
and not
```js
export interface RootObject {
  something: Something[];
}
export interface Something {
  x?: number | string;
}
```

**Comment by mknj** [comment]
it is the same as #5 
My problem is that i am creating jsonschema from my ts interface. The jsonschema will complain about "x":null, as `x?: number|string` means that the value must be number, string or the property must not exist.

Would it be possible to add an option for "null" handling?

**Comment by MariusAlch** [comment]
Fixed with recent commits
