### ISSUE TITLE
Possibility to add code as url parameters? A REST API even?

### ISSUE THREAD

**Issue by molnarmark** [MariusAlch/json-to-ts#6]
I'd like if this service would provide a way to pass json code in the URL, similarly in an API way. Maybe having a REST API wouldn't be so bad either, I don't think any of the 'rivals' support that as of now.

**Comment by MariusAlch** [comment]
This sounds like nice idea, I'll get to this when I'll have more time, for the meantime you could write your own small express app, shouldn't take too long
