### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by simon04** [MariusAlch/json-to-ts#7]
I'd love to use this tool on the commandline in a way like

```
npx json-to-ts source.json > interface.ts
```

**Comment by molnarmark** [comment]
@simon04 https://github.com/molnarmark/json-to-ts-cli :)

**Comment by danielpza** [comment]
@molnarmark I just made one not knowing about it lol. https://github.com/LeDDGroup/json-to-ts-cli. I think we should add a link to the cli packages on the README.

Some differences:

- Only inputs from stdin and outputs to stdout. (for now)
- Also accepts js objects besides json (eg reads `{ foo: 'baz' }` as `{ "foo": 'baz' }`)
- Not published to npm yet
