### ISSUE TITLE
Fails conversion from selection when single quotes are used

### ISSUE THREAD

**Issue by mubaidr** [MariusAlch/json-to-ts#9]
I am trying to convert a selection in my code to interface, but it fails as single comma is not a valid identifier in JSON schema. But this will be super helpful if i could just select an object from the code and be able to generate typescript interface for it.

**Comment by MariusAlch** [comment]
I want to target the JSON specification. You can get around this doing 
```typescript
JsonToTS(eval({'single': 'quotes'}))
```
